apiVersion: v1
kind: Service

metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      # The port for the cluster service
      port: 80
      targetPort: 8888 # Port for the internal containers
